// Regenerates src/db/migrations-data.ts: embeds every migration's raw SQL
// content (read from src/db/migrations/<tag>.sql, per the journal) as a
// plain string constant, so src/db/migrations.ts can apply migrations
// without any filesystem access. Needed because this app runs in a
// browser (Vite/jeep-sqlite+sql.js) as well as under Node (tests,
// scripts/build-dummy-db.ts), and drizzle-orm's own
// sqlite-proxy/migrator reads migration files via Node's fs module, which
// does not exist in a browser context — see migrations.ts's module
// comment for the full story (a real, ship-blocking bug this script's
// output exists to avoid).
//
// Run this (`npm run db:generate-data`) any time a new migration file is
// added under src/db/migrations/ — after `npm run db:generate` and any
// required hand-edits to the generated .sql file, not instead of them.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import journal from "../src/db/migrations/meta/_journal.json" with { type: "json" };

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = resolve(__dirname, "../src/db/migrations");
const OUT_PATH = resolve(__dirname, "../src/db/migrations-data.ts");

function toTsTemplateLiteral(content: string): string {
  return "`" + content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

const entries = (journal.entries as { tag: string }[]).map(({ tag }) => {
  const content = readFileSync(resolve(MIGRATIONS_DIR, `${tag}.sql`), "utf8");
  return { tag, content };
});

const header = `// Raw content of every migration SQL file under src/db/migrations/,
// embedded as string constants so they can be applied without any
// filesystem access — see migrations.ts's module comment for why.
// Generated by scripts/generate-migrations-data.ts; if a migration file
// changes or a new one is added, re-run \`npm run db:generate-data\` to
// regenerate this file to match — never hand-edit the object below.

export const MIGRATION_SQL_BY_TAG: Record<string, string> = {
`;

const body = entries.map(({ tag, content }) => `  ${JSON.stringify(tag)}: ${toTsTemplateLiteral(content)},`).join("\n");

writeFileSync(OUT_PATH, `${header}${body}\n};\n`);
console.log(`Wrote ${OUT_PATH} (${entries.length} migration${entries.length === 1 ? "" : "s"})`);
