// Generated by scripts/ingest/build-reference.ts — do not hand-edit.
// A content hash of reference.json, baked in at build time so
// src/db/reference-sync.ts can compare against it without re-hashing
// the full reference dataset on every app boot.
export const REFERENCE_DATA_VERSION = "88c3e1c6";
